### ISSUE TITLE
Is it possible to include a non-allocating method of enumerating members?

### ISSUE THREAD

**Issue by Soren025** [Tydude4Christ/Enums.NET#11]
I switched over to EnumsNET from my quickly made util class due to frustration of implementing what I wanted out of it when it already existed here all this time and more. The one thing I miss however is a means of enumerating the values of an enum without memory allocation. Is it possible to include this feature in some way?

**Comment by TylerBrinkley** [comment]
This was a 2.1.1 regression. It's been fixed in the source. I'll let you know when an update is released to NuGet.

**Comment by TylerBrinkley** [comment]
@Soren025 I just released Enums.NET 2.2.0 on NuGet which includes the fix for this issue.

**Comment by Soren025** [comment]
Nice!
