### ISSUE TITLE
netstandard2.0 is required in Enums.NET 2.3.0

### ISSUE THREAD

**Issue by LordMike** [Tydude4Christ/Enums.NET#18]
The changes made in #15 seem to mean that `Enums.NET 2.3.0` cannot run on `netstandard1.6`, even though `Enums.NET` targets `netstandard1.0`+.

https://www.nuget.org/packages/Enums.NET/2.3.0

On `dotnet restore`, I get the following:
```
> dotnet restore
  Restoring packages for C:\<--snip-->\HttpDownloader\HttpDownloader.csproj...
C:\<--snip-->\HttpDownloader\HttpDownloader.csproj : error NU1605: Detected package downgrade: NETStandard.Library from 2.0.0 to 1.6.1. Reference the package directly from the project to select a different version.
C:\<--snip-->\HttpDownloader\HttpDownloader.csproj : error NU1605:  HttpDownloader -> Enums.NET 2.3.0 -> NETStandard.Library (>= 2.0.0)
C:\<--snip-->\HttpDownloader\HttpDownloader.csproj : error NU1605:  HttpDownloader -> NETStandard.Library (>= 1.6.1)
  Restore failed in 193,86 ms for C:\<--snip-->\HttpDownloader\HttpDownloader.csproj.
```

On the nuget page, we can see this:
![image](https://user-images.githubusercontent.com/1027111/33995884-a35132e8-e0df-11e7-8d0d-74966ad1de3a.png)

**Comment by TylerBrinkley** [comment]
Just posted to the `dotnet/standard` repo [here](https://github.com/dotnet/standard/issues/606) for guidance.

You can set the .NET Standard implicit package version to 2.0.0 by changing your .csproj to use `<NetStandardImplicitPackageVersion>2.0.0</NetStandardImplicitPackageVersion>` but you're still able to target .NET Standard 1.6 in the target framework section of your .csproj. This will fix the error you're getting though I'd like to hear from Microsoft on how best this situation should be handled.

**Comment by TylerBrinkley** [comment]
It looks like I'm going to remove the explicitly set `NetStandardImplicitPackageVersion` and just let the SDK handle it. I'll post a version 2.3.1 with this change.

**Comment by TylerBrinkley** [comment]
This was updated with 26d27df19a6d17c20d91dba4afaef6151a046e19 and version 2.3.1 was uploaded to NuGet with this fix.
