### ISSUE TITLE
SelectList for DropDown Functionality

### ISSUE THREAD

**Issue by weedkiller** [Tydude4Christ/Enums.NET#20]
Hi, how can we support a SelectList with your lib,

```
public IEnumerable<SelectListItem> Creating_a_select_list(State selected)
{
    return State.GetAll().Select(
        x => new SelectListItem
        {
            Selected = x == selected,
            Text = x.Description,
            Value = x.Value.ToString()
        });
}
```

**Comment by TylerBrinkley** [comment]
Not sure, I don't use much MVC. Maybe something like this?

```c#
public IEnumerable<SelectListItem> Creating_a_select_list(State selected)
{
    return Enums.GetMembers<State>().Select(
        x => new SelectListItem
        {
            Selected = x.Value == selected,
            Text = x.AsString(EnumFormat.Description),
            Value = x.AsString()
        });
}
```

**Comment by weedkiller** [comment]
One more question, how do I ensure the selectlist from only loads items with flags, or unions 

for e.g. in this, I dont want to show `weekends/weekdays` or `All` as part of my selectlist option.

Also when I tried Enum.GetName() function it does not resolve after install the lib.

```
 enum DaysOfWeek
    {
        None = 0,
        Sunday = 1,
        Monday = 2,
        Tuesday = 4,
        Wednesday = 8,
        Thursday = 16,
        Friday = 32,
        Weekdays = Monday | Tuesday | Wednesday | Thursday | Friday,
        Saturday = 64,
        Weekend = Sunday | Saturday,
        All = Sunday | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday
    }
```
thanks.

**Comment by TylerBrinkley** [comment]
You could try `Enums.GetMembers<DaysOfWeek>(EnumMemberSelection.Flags)` or `DaysOfWeek.All.GetFlags()`.

**Comment by weedkiller** [comment]
I'm sorry my question was worded in correctly...

> One more question, how do I ensure the selectlist from only loads items **without** flags, or unions
> 
> for e.g. in this, I dont want to show weekends/weekdays or All as part of my selectlist op

tion.

**Comment by jnm2** [comment]
That's the same as figuring out whether the numeric value of each field is a power of two.
(https://graphics.stanford.edu/~seander/bithacks.html#DetermineIfPowerOf2)

```cs
values.Where(value =>
    (value != 0) && ((value & (value - 1)) == 0)
)
```

**Comment by jnm2** [comment]
@weedkiller Looks like you'd then use `Enums.GetMembers<DaysOfWeek>(EnumMemberSelection.Distinct)`

**Comment by jnm2** [comment]
Never mind me. I need to actually use this library finally. 😃

**Comment by jnm2** [comment]
Okay, so I'm curious. Can I use Enums.NET to get a list of all values with exactly one bit set, a la https://graphics.stanford.edu/~seander/bithacks.html#DetermineIfPowerOf2?

**Comment by TylerBrinkley** [comment]
@weedkiller `Enums.GetValues<DaysOfWeek>(EnumMemberSelection.Flags)` would return `Sunday` through `Saturday`.

@jnm2 If you want all values of the enum with exactly one bit set see above. If you have a value and want to split it out into a list of flags with exactly one bit set you would call the `GetFlags` extension method.
