### ISSUE TITLE
Support for Parsing ReadOnlySpan<char>

### ISSUE THREAD

**Issue by MichalBrylka** [Tydude4Christ/Enums.NET#25]
Hi,
would you be willing to add support for parsing ReadOnlySpan<char> any time soon ?

**Comment by TylerBrinkley** [comment]
I've looked into it and will probably implement it once .NET Standard 2.1 or .NET Core 3.0 releases. Internally Enums.NET uses `Dictionary` for parsing but there's currently no way of using a `ReadOnlySpan<char>` for `Dictionary` lookups. I created the issue https://github.com/dotnet/corefx/issues/31942 in order for that to be addressed but there's no word on whether that will be approved. If it's not approved support for parsing `ReadOnlySpan<char>` will require implementing a new dictionary type.

**Comment by MichalBrylka** [comment]
If you like, have a look on what I've got here (public TEnum Parse(ReadOnlySpan<char> input)):
https://gist.github.com/MichalBrylka/d01206f7aa2a5e0815de25d6abfd7406

I'm creating a no-alloc, decently fast library to parse various elements from text. I'm interested in parsing enums mine(our company's) way - i.e. only ignore case parsing is supported but adding support for other cases should be also easy. 

What I have in this gist is not necessary the fastest way (using compiled LINQ expressions is not optimized for speed, however I'm tempted to try: https://github.com/dadhi/FastExpressionCompiler).
It does not however allocate upon parsing - which is great. 

If I'll decide to replace this in near future, I'd go using parsing trees or trie:
https://en.wikipedia.org/wiki/Trie

What do you think ?

I also created a lot of automatic exploratory tests to hunt for parsing errors

**Comment by MichalBrylka** [comment]
ok, let's assume that we have as follows:
```csharp
[Flags]
public enum DaysOfWeek : byte
{
    Monday = 0b0_0000_0001,
    Tuesday = 0b0_0000_0010,
    Wednesday = 0b0_0000_0100,
    Thursday = 0b0_0000_1000,
    Friday = 0b0_0001_0000,
    Saturday = 0b0_0010_0000,
    Sunday = 0b_0100_0000,
    Weekdays = Monday | Tuesday | Wednesday | Thursday | Friday,
    Weekends = Saturday | Sunday,
    All = Weekdays | Weekends
}
```
for this enum by routine generates a code like this:
https://gist.github.com/MichalBrylka/1161760a854bb59cff5508a95d4edc6e
using expression trees. Here are some benchmarks (have a look at second row):

|                      Method |       Mean |     Error |    StdDev | Ratio |  Gen 0 | Allocated |
|---------------------------- |-----------:|----------:|----------:|------:|-------:|----------:|
|              ExpressionTree | 117.356 us | 2.1689 us | 2.1302 us |  1.00 |      - |         - |
|               GeneratedCode |   2.412 us | 0.0458 us | 0.0490 us |  0.02 |      - |         - |
|        NativeEnumIgnoreCase |  48.751 us | 1.0076 us | 1.1995 us |  0.42 | 0.7324 |    3169 B |

**Comment by TylerBrinkley** [comment]
I've added `ReadOnlySpan<char>` parsing support in the [reduce-static-footprint feature branch](https://github.com/TylerBrinkley/Enums.NET/tree/reduce-static-footprint) by implementing my own dictionary type. See [here](https://github.com/TylerBrinkley/Enums.NET/blob/581c61c78b693fb777a91f6c2a6f074be653a947/Src/Enums.NET/EnumCache.cs#L1537). It requires new API's for getting the hashcode of a span that are to be introduced in .NET Core 3.0 and thus will ship when .NET Core 3.0 is released.

**Comment by MichalBrylka** [comment]
thanks for info. So I looking forward to  .NET Core 3.0 release and I'll compare my solution with your. Cheers

**Comment by TylerBrinkley** [comment]
I've released `Enums.NET` v3.0 which includes `ReadOnlySpan<char>` parsing support. Please check it out.

**Comment by MichalBrylka** [comment]
THX. Seems to work. I'll try to check performance and compare it with my approach

**Comment by MichalBrylka** [comment]
Hi @TylerBrinkley 
please have a look at:
https://github.com/nemesissoft/Nemesis.TextParsers/blob/master/Benchmarks/EnumBench.cs#L17
and benchmarks starting with "EnumsDotNet" (EDN for short in result table)

These are mine results for target core 2.1:

|                      Method |     Mean | Ratio | Allocated |
|---------------------------- |---------:|------:|----------:|
|             EnumTransformer | 19.85 us |  1.00 |         - |
|               DedicatedCode | 19.91 us |  1.00 |         - |
| NativeEnumIgnoreCaseGeneric | 40.95 us |  2.06 |    3169 B |
|        NativeEnumIgnoreCase | 39.37 us |  1.98 |    3169 B |
|       NativeEnumObserveCase | 36.80 us |  1.85 |    3169 B |

I cannot use your lib with core 2.1 - obviously, so let's have a look at net core 3.0

|                      Method |     Mean | Ratio | Allocated |
|---------------------------- |---------:|------:|----------:|
|       EDN.GenericIgnoreCase | 32.37 us |  1.87 |         - |
|      EDN.GenericObserveCase | 32.21 us |  1.86 |         - |
|                  EDN.Unsafe | 29.49 us |  1.70 |         - |
|    EDN.NonGenericIgnoreCase | 32.88 us |  1.89 |    3120 B |
|   EDN.NonGenericObserveCase | 32.41 us |  1.87 |    3120 B |
|             EnumTransformer | 17.36 us |  1.00 |         - |
|               DedicatedCode | 17.21 us |  0.99 |         - |
| NativeEnumIgnoreCaseGeneric | 17.27 us |  0.99 |         - |
|        NativeEnumIgnoreCase | 24.37 us |  1.40 |    3121 B |
|       NativeEnumObserveCase | 17.12 us |  0.99 |         - |

Native (corefx) parsers are much better now even without overload for parsing ReadOnlySpan.  Mine code (EnumTransformer) is on par with corefx. Your methods are 2 times slower. Is is something I'm doing wrong with your API ?

**Comment by TylerBrinkley** [comment]
The advantage of parsing with a `ReadOnlySpan<char>` is that you're not allocating a string to pass into the parsing method. In your test cases your input is already a string and thus does not incur that penalty hence my solution doesn't provide any benefits there. It is surprising however that it's so much slower than the native approach, especially given that I've tested parsing on .NET Core 3.0 and have found `System.Enum` parsing to take around ~64%~ 28% more time generally though that is for single names. Perhaps my flag parsing performance could be improved.

**Comment by MichalBrylka** [comment]
Yup, I'm aware of that. But could you share your benchmark so I can modify mine to only compare parsing of ReadOnlySpan?

**Comment by TylerBrinkley** [comment]
I just realized my performance benchmarks were still comparing with the non-generic `Enum.Parse` method. I added the generic version and on .NET Core for names `System.Enum` only takes around 28% more time to execute. I'll be updating the chart and adding some flag enum parsing benchmarks so I can see where I can make improvements there as well.

**Comment by TylerBrinkley** [comment]
I just released v3.0.1 which includes parsing performance improvements. Please check it out. To make a fair comparison with parsing `string` vs `ReadOnlySpan<char>` I think you should do a `Substring` before passing the value to the parsing method. You can do a `Slice` instead for the `ReadOnlySpan<char>` parser.

**Comment by MichalBrylka** [comment]
ok, in 3.0.1 the performance "might" have slightly degraded although one should generally not compare microbenchmarks across multiple runs - but frankly other figures (mine and System.Enum) are consistent. See for yourself: https://github.com/nemesissoft/Nemesis.TextParsers/blob/master/Benchmarks/EnumBench.cs#L17
Results:

|                      Method |     Mean | Ratio | Allocated |
|---------------------------- |---------:|------:|----------:|
|       EDN.GenericIgnoreCase | 41.26 us |  2.36 |         - |
|      EDN.GenericObserveCase | 31.90 us |  1.83 |         - |
|                  EDN.Unsafe | 30.73 us |  1.76 |         - |
|    EDN.NonGenericIgnoreCase | 41.32 us |  2.37 |    3120 B |
|   EDN.NonGenericObserveCase | 30.79 us |  1.76 |    3120 B |
|             EnumTransformer | 17.45 us |  1.00 |         - |
|               DedicatedCode | 17.65 us |  1.01 |         - |
| NativeEnumIgnoreCaseGeneric | 17.97 us |  1.03 |         - |
|        NativeEnumIgnoreCase | 24.69 us |  1.42 |    3121 B |
|       NativeEnumObserveCase | 16.73 us |  0.96 |         - |



More over I've generated dedicated tests just for your cause:
https://github.com/nemesissoft/Nemesis.TextParsers/blob/master/Benchmarks/EnumBench.cs#L304
where I generate long string that is later converted to span and sliced for parsing. Same logic is used in every case. Results:

|                    Method |     Mean | Ratio | Allocated |
|-------------------------- |---------:|------:|----------:|
|     EDN.GenericIgnoreCase | 49.16 us |  2.43 |         - |
|    EDN.GenericObserveCase | 34.81 us |  1.72 |         - |
|                EDN.Unsafe | 33.22 us |  1.64 |         - |
|  EDN.NonGenericIgnoreCase | 52.67 us |  2.60 |    3120 B |
| EDN.NonGenericObserveCase | 34.86 us |  1.72 |    3120 B |
|           EnumTransformer | 20.25 us |  1.00 |         - |

**Comment by MichalBrylka** [comment]
this still leaves EDN slightly behind. I'm not saying it's an issue - performance is still good.  You might however remove these allocation if possible. Also - I'm treating EDN here as black box
