### ISSUE TITLE
Feature request...

### ISSUE THREAD

**Issue by markchipman** [Tydude4Christ/Enums.NET#32]
This looks like a very useful and interesting library.  I've been going through the test cases to see if a particular bit of functionality might be in the library... but alas couldn't see it in there.

What I'm hoping to find is an extension method to verify that an composite enum (bitwise ORing of multiple enum values) has One and only One member value of a specified Type.  Let me paint a picture of what I'm doing.  I'm utilizing several enums to represent ingredients and size attributes of a pizza like so:

public  class Pizza
{
enum pizzaSize
{
small,
medium,
large
} 

[Flags]
enum cheeseTopping
{
None = 0,
MozzerrellaX1 = 1, // normal amount of cheese
MozzerrellaX2 = 2, // double the amount of cheese
MozzerrellaX3 = 4 // three times the amount of cheese
}

[Flags]
enum pepperoniTopping
{
None = 0,
PepperoniX1 = 8,  //normal amount of pepperoni
PepperoniX2 = 16, // double the amount of pepperoni
PepperoniX3 = 32 // three times the amount of pepperoni
}

[Flags]
enum menuItems
{
smallCheeseOnlyPizza = pizzaSize.small | cheeseTopping.MozzerrellaX1,
smallDoubleCheeseOnlyPizza = pizzaSize.small | cheeseTopping.MozzerrellaX2
largeMegaPepperoniAndHumongousCheesePizza = pizzaSize.large | cheeseTopping.MozzerrellaX3 | pepperoniTopping.PepperoniX3
}
}
Now what I'm trying to achieve in a pizza-order validation method is to ensure that for each enum type [cheeseTopping, pepperoniTopping, etc.], there can only be ONE member type selected (ie. either PepperoniX1, PepperoniX2 or PepperoniX3, but not two of them or all three of them in the menuItems.largeMegaPepperoniAndHumongousCheesePizza composite enum). In other words... you only can have one of each enum member values for each ingredient in your pizza.

Can this be easily done using this library or is it something that could be added relatively easily?  
*******************************************************************************************************
One other quick question... when using [Flags], I understand that the maximum number of member enums which are assigned values using [Flags] in the class is limited because the values are hard-coded sized as int32 by design (thus I think you can have 127 members, thus a max value of 2^127 as maximum the int32 value).  Does your library increase this range by chance... to use perhaps a ulong (64bit) so that you could have vastly more [Flags]-based enums in the class)?  I just don't like the limitations imposed.  I really want ALOT of toppings :)

Thanks.

Regards,

Mark Chipman

**Comment by TylerBrinkley** [comment]
I don't think this is a good use of flag enums as the max number of options a flag enum can have is 64 using a `ulong` or `long`, one per bit and your proposed solution is quite unwieldy and not easily expandable. But to address your question you can check to see if there's only one flag selected by comparing the result of the `GetFlagCount` method with `1`, although I'm not sure how you would handle the composite enum, perhaps `&` it with all the types flags prior to calling `GetFlagCount`.
