### ISSUE TITLE
IsObsolete extension method

### ISSUE THREAD

**Issue by leandromoh** [Tydude4Christ/Enums.NET#35]
As well we have `IsDefined` and `IsValid`, would be nice to have the `IsObsolete` extension method.
I missed it today.

May I open a PR for this?

Prototype: 

```c#
public static bool IsObsolete<TEnum>(this TEnum value) 
    where TEnum : struct, Enum
{
    return typeof(TEnum)
        .GetField(value.ToString())
        .GetCustomAttributes(typeof(ObsoleteAttribute), false)
        ?.Length > 0;
}
```

**Comment by TylerBrinkley** [comment]
Sorry but I don't think this would be useful enough to warrant an extension method. Besides, you can implement it pretty simply like so.

```c#
value.GetAttributes().Has<ObsoleteAttribute>();
```

**Comment by leandromoh** [comment]
> Sorry but I don't think this would be useful enough to warrant an extension method. Besides, you can implement it pretty simply like so.
> 
> ```cs
> value.GetAttributes().Has<ObsoleteAttribute>();
> ```

I did not know about this workaround! thanks!
