### ISSUE TITLE
Type Parameters

### ISSUE THREAD

**Issue by InteXX** [Tydude4Christ/Enums.NET#38]
Does `Enums.NET` enable the use of an enum as a type parameter?

If so, what would be the proper usage syntax?

**Comment by TylerBrinkley** [comment]
You've always been able to specify any type as a type parameter but only until C# 7.3 could you constrain a generic type or method to just enums using the Enum constraint. Below's an example.

```c#
public bool HasFlag<TEnum>(TEnum value, TEnum other)
    where TEnum : struct, Enum => value.HasFlag(other);
```

which could be used like so
```c#
var value = HasFlag(AttributeTargets.All, AttributeTargets.Class);
```

This library simply provides a bunch of replacement and helper methods for the built-in `System.Enum` methods that have much better performance in most cases.

**Comment by InteXX** [comment]
Got it, thanks.
