### ISSUE TITLE
HasAnyFlags fails while HasFlag is not 

### ISSUE THREAD

**Issue by apobekiaris** [Tydude4Christ/Enums.NET#39]
unfortunately cannot repro it in a clean sample, but somewhere deep in my modules the next call is not valid, but when I use the HasFlag method it is

![image](https://user-images.githubusercontent.com/159464/137630183-549557df-bfec-482b-a618-f655924ee787.png)

**Comment by TylerBrinkley** [comment]
Is there an error or does it return `false` when `true` is expected? What is the base type of the `ObjectModification` enum, `int`, `byte`, etc? What version of `Enums.NET` are you using? What runtime version is this on, .NET Framework 4.8, .NET Core 3.1, etc?

**Comment by apobekiaris** [comment]
no error, just wrong result, ObjectModification is int, this is a test that runs nunit on .net5,0

**Comment by apobekiaris** [comment]
from Rider IDE if it matters

**Comment by TylerBrinkley** [comment]
Closing due to age.
