### ISSUE TITLE
FlagEnums.GetFlags gets stuck on V4.0.0 (and 3.0.3)

### ISSUE THREAD

**Issue by urikanonov** [Tydude4Christ/Enums.NET#40]
Both the "generic" enum.GetFlags() and non-generic version of GetFlags(Type enumType, object value) get completely stuck (likely infinite loop inside) on certain inputs.
The GetFlags method returns but either enumerating the input or using random access (flags[0]) will cause execution to get stuck.

The code below will repro the issue. Tested on both net462 an net6.0 and with both V3.0.3 and V4.0.0.
Attaching zip with SLN that includes a single project with a single Program.cs containing the code below.

```
public static void Main(string[] args)
{
    MyEnum value = (MyEnum)1610612801;
    var flags = value.GetFlags();
    Trace.WriteLine($"{string.Join(",", flags)}"); // <-- This is stuck during enumeration of flags

    var flags2 = FlagEnums.GetFlags(typeof(MyEnum), value);
    Trace.WriteLine($"{string.Join(",", flags2)}"); // <-- This is stuck during enumeration of flags
}

[Flags]
public enum MyEnum
{
    Unknown = 0x0,
    Val1 = 0x1,
    Val4 = 0x4,
    Val8 = 0x8,
    Val10 = 0x10,
    Val20 0 = 0x40,
    Val80 = 0x80,
}

```
[EnumsNetStuck.zip](https://github.com/TylerBrinkley/Enums.NET/files/10034593/EnumsNetStuck.zip)

**Comment by urikanonov** [comment]
@TylerBrinkley  - Can you please take a look? This is a high severity issue.

**Comment by TylerBrinkley** [comment]
Thank you for posting this issue. I plan to look at this today. I was having some SDK issues with Visual Studio when I tried looking at this yesterday.
