### ISSUE TITLE
Missing classes in tests

### ISSUE THREAD

**Issue by spmadeira** [Tydude4Christ/Enums.NET#43]
Tried cloning repo and running tests locally and ran into these errors:
```
The type or namespace name 'BooleanEnum' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'CharEnum' could not be found (are you missing a using directive or an assembly reference?)
```

They are present in a good bit of the test code, for example in file EnumsTest.cs:

```csharp
        public void GetUnderlyingType()
        {
            Assert.AreEqual(typeof(sbyte), GetUnderlyingType<SByteEnum>());
            Assert.AreEqual(typeof(byte), GetUnderlyingType<ByteEnum>());
            Assert.AreEqual(typeof(short), GetUnderlyingType<Int16Enum>());
            Assert.AreEqual(typeof(ushort), GetUnderlyingType<UInt16Enum>());
            Assert.AreEqual(typeof(int), GetUnderlyingType<Int32Enum>());
            Assert.AreEqual(typeof(uint), GetUnderlyingType<UInt32Enum>());
            Assert.AreEqual(typeof(long), GetUnderlyingType<Int64Enum>());
            Assert.AreEqual(typeof(ulong), GetUnderlyingType<UInt64Enum>());
            Assert.AreEqual(typeof(bool), GetUnderlyingType<BooleanEnum>());   <<<
            Assert.AreEqual(typeof(char), GetUnderlyingType<CharEnum>());      <<<
        }
```

I noticed that they were removed in this commit https://github.com/TylerBrinkley/Enums.NET/commit/63a04672c04d1f19b0e3a2835a69c64e32338ab7 . Should they be re-implemented, or should the tests be updated to no longer reference them? Wanted to raise some awareness on this.

**Comment by TylerBrinkley** [comment]
Those enums are in the `SpecialtyEnums.dll` referenced here. https://github.com/TylerBrinkley/Enums.NET/blob/master/Src/Enums.NET.Test/Enums.NET.Test.csproj#L30

They're not referenced from source since boolean and char enums are not able to be represented in c#. Is it failing to load that dll?

**Comment by spmadeira** [comment]
Oh, interesting. I had to retarget the projects to match the local .NET versions I have installed, that may have caused the DLLs to not load. I'll give it a try later with the project default targets and report back.

**Comment by spmadeira** [comment]
Seems to have been issue on my side, apologies and closing.

**Comment by TylerBrinkley** [comment]
Glad to hear you got it working. I'm sure there's probably some things I could do to make sure it's easier to build since I haven't touched it in awhile.
