### ISSUE TITLE
Is this library depracated?

### ISSUE THREAD

**Issue by m-demydiuk** [Tydude4Christ/Enums.NET#44]
Hello!
I used this amazing library for many years on various projects. Now I have a new project that will be written with .net8. 
I see Enums.Net was last time updated about a year ago. Is this project deprecated? Can I safely use it with latest .net (8 in this case)?

Thanks!

**Comment by TylerBrinkley** [comment]
Thanks for using Enums.NET. This library is not deprecated but as there hasn't been much need for maintenance or improvements I haven't pushed any updates recently. It continues to work in its targeted frameworks and above and will work in .NET 8. That being said the performance benefits of this library compared with the equivalent System.Enum methods has become less in recent years and even more so with .NET 8, however there is a lot of functionality that is unlikely to make it into System.Enum and thus the library still remains useful in my opinion.

**Comment by m-demydiuk** [comment]
@TylerBrinkley thanks for the quick reply!
