### ISSUE TITLE
Build issue with nuget and fody

### ISSUE THREAD

**Issue by PandaWood** [Tydude4Christ/Enums.NET#5]
Apologies, might be machine, but I cannot build this project.
Download, run **runbuild.cmd** but always get this error (below)

I tried running nuget console: Update-Package –reinstall
Seems to update the right package.
Still doesn't fix it.
Could be my machine or the wonder of NuGet but I've had to give up.

  **C:\code\Enums.NET\Working\Src\Enums.NET\Enums.NET.csproj(93,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Fody.1.29.4\build\dotnet\Fody.targets.**

**Comment by TylerBrinkley** [comment]
You're right. I had to hack the build a bit to get it to work with .NET Standard. I just made a commit that should fix this issue for you.

**Comment by TylerBrinkley** [comment]
I'm assuming this fixed it for you. I'm going to close this issue and if it's not fixed I'll reopen.

**Comment by PandaWood** [comment]
Sorry for the delay. I can confirm this is fixed... build totally works.

**Comment by TylerBrinkley** [comment]
No problem. Glad to hear it.
