### ISSUE TITLE
Actually it is possible to have an enum constraint for a method's generic type parameter

### ISSUE THREAD

**Issue by strohhut** [Tydude4Christ/Enums.NET#6]
You write "There is currently no way to constrain a type or method's generic type parameter to an enum in C#.".

Please consider [this](http://stackoverflow.com/a/1416660) useful technique before saying it isn't possible.

**Comment by TylerBrinkley** [comment]
Wow, that's a pretty clever way to get around the problem. Thanks for letting me know about it. Unfortunately it doesn't work with extension methods so that technique wouldn't work with this library nor would I want to make a breaking change like that. I'll update the readme accordingly.
