### ISSUE TITLE
[Question] Enums in Attributes

### ISSUE THREAD

**Issue by RandyBuchholz** [Tydude4Christ/Enums.NET#8]
I haven't tried this out yet, but it looks really good. I came across the library when researching enums as generic constraints. Another area where enums aren't supported well by the framework is in attribute parameters. Does this library help in that area? If not, is that something that could be added?

**Comment by TylerBrinkley** [comment]
Thanks. What issues do you have with enum attribute parameters? I've never had any issues with that before.

**Comment by RandyBuchholz** [comment]
MS changed attributes so they no longer take an enum as a parameter value. I'm not sure when - I'm using Core.
```
public class ProcessAttribute : Attribute, IRouteTemplateProvider {
    public ProcessAttribute(Enum route) { ...

public enum Path { One, Two }

[Process(Path.One)]
public IActionResult Action() {
```
Gives the error
"Attribute constructor parameter 'route' has type 'Enum', which is not a valid attribute parameter type"

**Comment by jnm2** [comment]
@RandyBuchholz I know for sure that enums work in attributes in .NET Core. Why wouldn't you use:

```c#
public class ProcessAttribute : Attribute, IRouteTemplateProvider {
    public ProcessAttribute(Path route) { ...
```

**Comment by RandyBuchholz** [comment]
I don't always know what Enum will be passed, only that it will be an Enum. I am processing to the Enum itself, not just the value.

BTW - My wording was wrong. I should have said, "MS changed attributes so they no longer take ~enum~ Enum as a parameter ~value~ type.

**Comment by TylerBrinkley** [comment]
Can you use `object` instead?

**Comment by RandyBuchholz** [comment]
Yes. That's what I'm doing now. When I saw what you were doing with enums I thought there might be an opportunity to tighten that up a little.

**Comment by jnm2** [comment]
Just out of curiosity, how bad would it be to define a constructor per expected enum type? It seems leaky to me to accept just any enum.

Also I'd be super interested in following an issue if you started one at https://github.com/dotnet/coreclr/issues. It's a potential cross-compiling issue if .NET Framework supports `Enum` attribute parameters and .NET Core doesn't.

**Comment by jnm2** [comment]
@RandyBuchholz also, I'd be super interested in following an issue if you started one at https://github.com/dotnet/coreclr/issues. It's a potential cross-compiling issue if .NET Framework supports `Enum` attribute parameters and .NET Core doesn't.

**Comment by RandyBuchholz** [comment]
@jnm2 Not as leaky as accepting `object`, lol. It's part of a framework, and being able to process any `Enum` is necessary.

If I recall correctly, the change may impact the whole C# stack. When I get a chance, I'll check to see if it's still supported on Framework. If so, I'll open an issue and update here.

**Comment by TylerBrinkley** [comment]
Closing issue as this is a .NET Core problem.
